#!/usr/bin/env bash
# ============================================================================
# Hubers Git Multi-Account Setup
# ============================================================================
# This script sets up git with multiple GitHub/GitLab accounts.
# 
# How it works:
# - Personal identity is the DEFAULT (works everywhere)
# - Work/other accounts OVERRIDE in specific folders
# - Uses SSH keys per account
# - Uses git's includeIf for automatic identity switching
#
# Folder structure:
#   ~/hubers-devtools/           → Personal (default)
#   ~/any-other-folder/          → Personal (default)
#   ~/git/mhubers/               → Personal (explicit, for reference)
#   ~/git/your-work-org/            → Work (override)
#   ~/git/bitbucket/             → Bitbucket (override)
#
# To add another account:
#   1. Add folder, email, key variables below
#   2. Add includeIf block in the gitconfig section
#   3. Add account config section
#   4. Re-run this script
# ============================================================================

set -e

echo "🔧 Hubers Git Multi-Account Setup"
echo "══════════════════════════════════════════════════════════════"
echo ""

# ============================================================================
# CONFIG - Edit these for your accounts
# ============================================================================

# Personal (DEFAULT - used everywhere unless overridden)
PERSONAL_NAME="mark-hubers"
PERSONAL_EMAIL="mhubers@gmail.com"
PERSONAL_KEY="$HOME/.ssh/git_personal.pem"
PERSONAL_FOLDER="$HOME/git/mhubers"

# Work account
WORK_NAME="Mark Hubers"
WORK_EMAIL="your-name@your-company.com"
WORK_KEY="$HOME/.ssh/git_your-company_bu.pem"
WORK_FOLDER="$HOME/git/your-work-org"

# Bitbucket account (update these with real values)
BITBUCKET_NAME="mark-hubers"
BITBUCKET_EMAIL="mhubers@gmail.com"
BITBUCKET_KEY="$HOME/.ssh/git_bitbucket.pem"
BITBUCKET_FOLDER="$HOME/git/bitbucket"

# ============================================================================
# CREATE FOLDERS
# ============================================================================
echo "📁 Creating git folders..."
mkdir -p "$PERSONAL_FOLDER"
mkdir -p "$WORK_FOLDER"
mkdir -p "$BITBUCKET_FOLDER"
echo "   ✓ $PERSONAL_FOLDER"
echo "   ✓ $WORK_FOLDER"
echo "   ✓ $BITBUCKET_FOLDER"
echo ""

# ============================================================================
# GENERATE SSH KEYS (if they don't exist)
# ============================================================================
echo "🔐 Checking SSH keys..."

generate_key() {
    local key_path="$1"
    local email="$2"
    local name="$3"
    
    if [ -f "$key_path" ]; then
        echo "   ✓ $name key exists: $key_path"
    else
        echo "   Generating $name key..."
        ssh-keygen -t ed25519 -C "$email" -f "$key_path" -N ""
        echo "   ✓ Created: $key_path"
    fi
}

generate_key "$PERSONAL_KEY" "$PERSONAL_EMAIL" "Personal"
generate_key "$WORK_KEY" "$WORK_EMAIL" "Work"
generate_key "$BITBUCKET_KEY" "$BITBUCKET_EMAIL" "Bitbucket"
echo ""

# ============================================================================
# BACKUP EXISTING CONFIG
# ============================================================================
if [ -f "$HOME/.gitconfig" ]; then
    backup="$HOME/.gitconfig.backup.$(date +%Y%m%d-%H%M%S)"
    echo "📦 Backing up existing .gitconfig to $backup"
    cp "$HOME/.gitconfig" "$backup"
fi

# ============================================================================
# MAIN GIT CONFIG (with personal as default)
# ============================================================================
echo "📝 Creating ~/.gitconfig..."

cat > "$HOME/.gitconfig" <<EOF
# ============================================================================
# Git Configuration - Multi-Account Setup
# ============================================================================
# Personal identity is DEFAULT (works everywhere)
# Work/other accounts override in specific folders
# 
# Generated by: hubers_git_setup.sh
# ============================================================================

# Default identity (Personal - used everywhere unless overridden)
[user]
    name = $PERSONAL_NAME
    email = $PERSONAL_EMAIL

[core]
    excludesfile = ~/.gitignore
    pager = delta
    # Default SSH key (personal)
    sshCommand = "ssh -i $PERSONAL_KEY"

[commit]
    template = ~/.stCommitMsg

# ============================================================================
# Aliases
# ============================================================================
[alias]
    s = status
    st = status
    ci = commit
    co = checkout
    cob = checkout -b
    del = branch -D
    br = branch --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(contents:subject) %(color:green)(%(committerdate:relative)) [%(authorname)]' --sort=-committerdate
    save = !git add -A && git commit -m 'chore: savepoint'
    undo = reset HEAD~1 --mixed
    res = !git reset --hard
    done = !git push origin HEAD
    lg = !git log --pretty=format:"%C(magenta)%h%Creset -%C(red)%d%Creset %s %C(dim green)(%cr) [%an]" --abbrev-commit -30
    listremote = remote show origin

# ============================================================================
# Merge & Diff Tools
# ============================================================================
[merge]
    tool = vscode
    conflictstyle = diff3

[mergetool "vscode"]
    cmd = "code --wait"

[interactive]
    diffFilter = delta --color-only

[delta]
    navigate = true
    light = false
    side-by-side = true
    line-numbers = true

[diff]
    colorMoved = default

# ============================================================================
# Account Overrides (includeIf)
# ============================================================================
# These override the default identity for specific folders
# Personal folder (same as default, but explicit - good for reference)
[includeIf "gitdir:$PERSONAL_FOLDER/"]
    path = ~/.gitconfig_mhubers

# Work folder - overrides to work identity
[includeIf "gitdir:$WORK_FOLDER/"]
    path = ~/.gitconfig_your-work-org

# Bitbucket folder - overrides to bitbucket identity
[includeIf "gitdir:$BITBUCKET_FOLDER/"]
    path = ~/.gitconfig_bitbucket
EOF

echo "   ✓ Created ~/.gitconfig"

# ============================================================================
# ACCOUNT-SPECIFIC CONFIGS
# ============================================================================
echo "📝 Creating account configs..."

# Personal account config
cat > "$HOME/.gitconfig_mhubers" <<EOF
# Personal GitHub account (mhubers@gmail.com)
[user]
    name = $PERSONAL_NAME
    email = $PERSONAL_EMAIL
[core]
    sshCommand = "ssh -i $PERSONAL_KEY"
EOF
echo "   ✓ Created ~/.gitconfig_mhubers"

# Work account config
cat > "$HOME/.gitconfig_your-work-org" <<EOF
# Work GitHub account (your-company)
[user]
    name = $WORK_NAME
    email = $WORK_EMAIL
[core]
    sshCommand = "ssh -i $WORK_KEY"
EOF
echo "   ✓ Created ~/.gitconfig_your-work-org"

# Bitbucket account config
cat > "$HOME/.gitconfig_bitbucket" <<EOF
# Bitbucket account
[user]
    name = $BITBUCKET_NAME
    email = $BITBUCKET_EMAIL
[core]
    sshCommand = "ssh -i $BITBUCKET_KEY"
EOF
echo "   ✓ Created ~/.gitconfig_bitbucket"

echo ""

# ============================================================================
# SSH CONFIG (optional but helpful)
# ============================================================================
echo "📝 Checking SSH config..."

SSH_CONFIG="$HOME/.ssh/config"
if [ ! -f "$SSH_CONFIG" ]; then
    cat > "$SSH_CONFIG" <<EOF
# GitHub - Personal
Host github.com-personal
    HostName github.com
    User git
    IdentityFile $PERSONAL_KEY

# GitHub - Work
Host github.com-work
    HostName github.com
    User git
    IdentityFile $WORK_KEY

# Bitbucket
Host bitbucket.org
    HostName bitbucket.org
    User git
    IdentityFile $BITBUCKET_KEY

# Default GitHub (personal)
Host github.com
    HostName github.com
    User git
    IdentityFile $PERSONAL_KEY
EOF
    echo "   ✓ Created ~/.ssh/config"
else
    echo "   ℹ️  ~/.ssh/config already exists (not modified)"
fi

echo ""

# ============================================================================
# DONE
# ============================================================================
echo "══════════════════════════════════════════════════════════════"
echo "✅ Git Multi-Account Setup Complete!"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "📁 Folder → Identity mapping:"
echo "   ~/hubers-devtools/        → Personal (default)"
echo "   ~/anything-else/          → Personal (default)"
echo "   ~/git/mhubers/            → Personal (explicit)"
echo "   ~/git/your-work-org/         → Work"
echo "   ~/git/bitbucket/          → Bitbucket"
echo ""
echo "🔐 SSH Keys:"
echo "   Personal:  $PERSONAL_KEY"
echo "   Work:      $WORK_KEY"
echo "   Bitbucket: $BITBUCKET_KEY"
echo ""
echo "📋 Next steps:"
echo "   1. Add SSH public keys to GitHub/GitLab/Bitbucket:"
echo "      cat $PERSONAL_KEY.pub"
echo "      cat $WORK_KEY.pub"
echo ""
echo "   2. Test with:"
echo "      ssh -T git@github.com"
echo ""
echo "   3. Clone repos to the right folders:"
echo "      cd ~/git/your-work-org && git clone git@github.com:your-company/repo.git"
echo "      cd ~/git/mhubers && git clone git@github.com:mhubers/repo.git"
echo ""
echo "💡 To add another account:"
echo "   1. Edit this script (add variables at top)"
echo "   2. Add includeIf block"
echo "   3. Add account config section"
echo "   4. Re-run: ./hubers_git_setup.sh"
echo ""
